# Generated by Django 6.0.4 on 2026-04-16 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('documento_identidad', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El documento de identidad solo puede contener caracteres alfanuméricos.', regex='^[0-9A-Za-z]+$')])),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('fecha_asistencia', models.DateField()),
                ('hora_ingreso', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('presente', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
