# Generated by Django 5.1.3 on 2026-04-16 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitante', models.CharField(help_text='Nombre completo del solicitante', max_length=150)),
                ('documento_identidad', models.CharField(help_text='Documento de identidad (cedula, pasaporte, etc.)', max_length=50, validators=[django.core.validators.RegexValidator(message='El documento de identidad solo puede contener caracteres alfanuméricos.', regex='^[0-9A-Za-z]+$')])),
                ('correo_electronico', models.EmailField(help_text='Correo electrónico para contacto', max_length=254)),
                ('telefono_contacto', models.CharField(help_text='Teléfono de contacto', max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono solo puede contener dígitos, +, -, paréntesis y espacios.', regex='^[0-9+\\-\\s()]+$')])),
                ('tipo_solicitud', models.CharField(choices=[('académica', 'Académica'), ('administrativa', 'Administrativa'), ('técnica', 'Técnica'), ('otra', 'Otra')], help_text='Categoría de la solicitud', max_length=20)),
                ('asunto', models.CharField(help_text='Resumen breve del tema de la solicitud', max_length=200)),
                ('descripcion_detallada', models.TextField(help_text='Descripción completa y detallada de la solicitud')),
                ('fecha_solicitud', models.DateField(auto_now_add=True, help_text='Fecha en que se registró la solicitud')),
                ('archivo_adjunto', models.FileField(blank=True, help_text='Archivo adjunto (opcional)', null=True, upload_to='solicitudes_adjuntos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'txt'], message='Solo se permiten archivos PDF, DOC, DOCX, XLS, XLSX, JPG, JPEG, PNG o TXT.')])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
